[project]
name = "mcp-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "aiosqlite>=0.21.0",
    "fastmcp>=2.11.0",
    "mcp[cli]>=1.12.3",
    "starlette>=0.47.2",
]
